# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.roll_min_var <- function(sigma, total, lower, upper) {
    .Call(`_rollport_roll_min_var`, sigma, total, lower, upper)
}

.roll_max_return <- function(mu, sigma, total, lower, upper) {
    .Call(`_rollport_roll_max_return`, mu, sigma, total, lower, upper)
}

.roll_max_utility <- function(mu, sigma, gamma, total, lower, upper) {
    .Call(`_rollport_roll_max_utility`, mu, sigma, gamma, total, lower, upper)
}

