# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.roll_min_var <- function(sigma, mu, target, total, lower, upper) {
    .Call(`_rolloptim_roll_min_var`, sigma, mu, target, total, lower, upper)
}

.roll_max_mean <- function(mu, sigma, target, total, lower, upper) {
    .Call(`_rolloptim_roll_max_mean`, mu, sigma, target, total, lower, upper)
}

.roll_max_utility <- function(mu, sigma, lambda, total, lower, upper) {
    .Call(`_rolloptim_roll_max_utility`, mu, sigma, lambda, total, lower, upper)
}

.roll_min_rss <- function(xx, xy, total, lower, upper) {
    .Call(`_rolloptim_roll_min_rss`, xx, xy, total, lower, upper)
}

